"""
Plotting utilities.
These are all fairly implementation specific right now,
they should be refactored to rely on more generic units.
"""

import os

import matplotlib.pyplot as plt
import numpy as np
from jaxtyping import Float
from matplotlib.colors import SymLogNorm
from pixell import enmap
from sotodlib.core import AxisManager

from .beam_utils import radial_profile

plt.rcParams["image.cmap"] = "coolwarm"  # "RdGy_r"


def plot_map(
    data: Float[np.ndarray, "nx ny"] | enmap.ndmap,
    posmap: Float[np.ndarray, "2 nx ny"] | enmap.ndmap,
    pixsize: float,
    extent: float,
    cent: tuple[float, float],
    plot_dir: str,
    title: str,
    comp: str = "T",
    log: bool = False,
    log_thresh: float = 1e-3,
    append: str = "",
    units: str = '"',
):
    """
    Plot a beam map using `imshow` using the `coolwarm` colormap.
    This also plots the profile of the map.

    Parameters
    ----------
    data : Float[np.ndarray, "nx ny"] | enmap.ndmap
        The beam map to plot.
    posmap : Float[np.ndarray, "2 nx ny"] | enmap.ndmap
        The position map for the beam map.
        Should be generated by `enmap.posmap`.
    extent : float
        The radius of the plot to make in the same units as `posmap`.
    cent : tuple[float, float]
        The center of the beam map in the same units as `posmap`.
    plot_dir : str
        The directory to save plots to.
    title : str
        The base title of the plot.
        The full title will have the format "{title} {comp} {append} {'log10'*log}".
        The output file will use the full title as the filename but with whitespace replaced by '_'
        and 'map' or 'prof' inserted between "{title}" and "{comp}" depending on which plot it is.
    comp : str, default: "T"
        The comp of the map we are plotting.
        Should be "T", "Q", "U", "Qr", or "Ur".
    log : bool, default: True
        If True then plot the log10 of the beam instead.
        This uses a symetric log norm, or signs are preserved.
    log_thresh : float, default: 1e-3
        The threshold at which the log plot transitions to linear to avoid issues near values of 0.
    append : str, default: ""
        String to append ti title and filename.
        See `title` for details.
    units : str, default: '"'
        The units of `posmap` to appear in axes labels.
    """
    plt.close()
    # Restrict to our local patch (oversample by 2)
    r = np.sqrt((posmap[0] - cent[1]) ** 2 + (posmap[1] - cent[0]) ** 2)
    ext_msk = r <= extent * np.sqrt(2)
    w = np.where(ext_msk)
    ext_sl = (
        slice(np.min(w[0]), np.max(w[0]) + 1),
        slice(np.min(w[1]), np.max(w[1]) + 1),
    )
    data = data[ext_sl]
    posmap = (posmap[0][ext_sl], posmap[1][ext_sl])

    # Use posmap to setup coordinates
    # posmap, pixsize, extent, and cent must all be in the same units
    # We are assuming square pixels here
    plt_extent = (posmap[1].max(), posmap[1].min(), posmap[0].min(), posmap[0].max())

    # Get radial profile and plot map with appropriate norm
    _norm = None
    label = f"_{comp}"
    if append != "":
        label += f"_{append}"
    rsq = (posmap[0] - cent[1]) ** 2 + (posmap[1] - cent[0]) ** 2
    rcent = np.unravel_index(np.argmin(rsq), data.shape)[::-1]
    rprof = radial_profile(
        data,
        (int(rcent[0]), int(rcent[1])),
    )[: int(0.5 * min(*data.shape))]
    if log:
        _norm = SymLogNorm(linthresh=log_thresh, clip=True, vmin=-1, vmax=1)
        label += f"_log10"
        with np.errstate(divide="ignore", invalid="ignore"):
            rprof = np.sign(rprof) * np.log10(np.abs(rprof))
        plt.imshow(data, origin="lower", extent=plt_extent, norm=_norm)
    else:
        vminmax = np.max(np.abs(data)[rsq < extent**2])
        plt.imshow(
            data, origin="lower", extent=plt_extent, vmin=-1 * vminmax, vmax=vminmax
        )
    plt.colorbar()
    plt.grid()
    plt.xlabel(f"Xi ({units})")
    plt.ylabel(f"Eta ({units})")
    plt.title(f"{title}{label.replace('_', ' ')}")

    plt.xlim((cent[0] - extent, cent[0] + extent))
    plt.ylim((cent[1] - extent, cent[1] + extent))
    plt.savefig(os.path.join(plot_dir, f"{title.replace(' ', '_')}_map{label}.png"))

    # Profile
    plt.close()
    x = np.linspace(0, pixsize * len(rprof), len(rprof))
    plt.plot(x, rprof)
    plt.xlabel(f"Radius ({units})")
    plt.title(f"{title}{label.replace('_', ' ')}")
    plt.xlim((0, extent))
    plt.savefig(
        os.path.join(plot_dir, f"{title.replace(' ', '_')}_prof{label}.png"),
        bbox_inches="tight",
    )


def plot_map_complete(
    data: Float[np.ndarray, "nx ny"] | enmap.ndmap,
    posmap: Float[np.ndarray, "2 nx ny"] | enmap.ndmap,
    pixsize: float,
    extent: float,
    cent: tuple[float, float],
    plot_dir: str,
    title: str,
    comps: str = "TQU",
    log_thresh: float = 1e-3,
    append: str = "",
    units: str = '"',
    lognorm: float = 1.0,
    qrur: bool = False,
):
    """
    Wrapper for `plot_map` that plots all comps in both linear and log scales.

    Parameters
    ----------
    data : Float[np.ndarray, "nx ny"] | enmap.ndmap
        The beam map to plot.
    posmap : Float[np.ndarray, "2 nx ny"] | enmap.ndmap
        The position map for the beam map.
        Should be generated by `enmap.posmap`.
    extent : float
        The radius of the plot to make in the same units as `posmap`.
    cent : tuple[float, float]
        The center of the beam map in the same units as `posmap`.
    plot_dir : str
        The directory to save plots to.
    title : str
        The base title of the plot.
        The full title will have the format "{title} {comp} {append} {'log10'*log}".
        The output file will use the full title as the filename but with whitespace replaced by '_'
        and 'map' or 'prof' inserted between "{title}" and "{comp}" depending on which plot it is.
    comps : str, default: "TQU"
        The comps of the map we are plotting.
        Should be "T" or "TQU".
    log_thresh : float, default: 1e-3
        The threshold at which the log plot transitions to linear to avoid issues near values of 0.
    append : str, default: ""
        String to append ti title and filename.
        See `title` for details.
    units : str, default: '"'
        The units of `posmap` to appear in axes labels.
    lognorm : float, default: 1
        Value to normalize map by before plotting in log scale.
        All comps are normalized by this factor.
        This is useful for seeing the polarization of the beam relative
        to the peak of the temperature beam.
    qrur : bool, default: False
        If True then also plot the radial QU maps.
        This will raise an error if Q and U are not in `comps`.
    """
    if len(data.shape) == 2:
        data = data[None, ...]
    for i, comp in enumerate(comps):
        for log in (False, True):
            plot_map(
                data[i] * (lognorm * log + (not log)),
                posmap,
                pixsize,
                extent,
                cent,
                plot_dir,
                title,
                comp=comp,
                log=log,
                log_thresh=log_thresh,
                append=append,
                units=units,
            )
    if not qrur:
        return
    if "Q" not in comps or "U" not in comps:
        raise ValueError("Cannot plot Qr and Ur without Q and U")
    Q = data[comps.find("Q")]
    U = data[comps.find("U")]
    eta, xi = posmap
    theta = np.arctan2(eta, xi)
    Q_r = Q * np.cos(2 * theta) + U * np.sin(2 * theta)
    U_r = U * np.cos(2 * theta) - Q * np.sin(2 * theta)
    for dat, comp in [(Q_r, "Qr"), (U_r, "Ur")]:
        for log in (False, True):
            plot_map(
                dat * (lognorm * log + (not log)),
                posmap,
                pixsize,
                extent,
                cent,
                plot_dir,
                title,
                comp=comp,
                log=log,
                log_thresh=log_thresh,
                append=append,
                units=units,
            )


def plot_tod(
    aman: AxisManager,
    sig_filt: Float[np.ndarray, "ndet nsamp"],
    tod_plot_dir: str,
    file_label: str,
    max_dets: int,
):
    """
    Plot a TOD and its filtered signal.

    Parameters
    ----------
    aman : AxisManager
        A TOD containing the unfiltered signal.
    sig_filt : Float[np.ndarray, "ndet nsamp"]
        The filtered signal.
    tod_plot_dir : str
        The directory to save plots to.
    file_label : str
        String to determine the file name.
        For the unfiltered signal the file is "{file_label}_tod.png".
        For the filtered signal the file is "{file_label}_tod_filt.png"
    max_dets : str
        The maximum number of detectors to plot.
        If `ndets` is greated than `max_dets` then the first `max_dets`
        detectors are plotted.
    """
    plt.close()

    plt.plot(np.array(aman.signal)[:max_dets].T, alpha=0.3)
    plt.xlabel("Samples")
    plt.ylabel("Signal (pW)")
    plt.savefig(os.path.join(tod_plot_dir, f"{file_label}_tod.png"))
    plt.close()

    plt.plot(sig_filt[:max_dets].T, alpha=0.3)
    plt.xlabel("Samples")
    plt.ylabel("Filtered Signal (pW)")
    plt.savefig(os.path.join(tod_plot_dir, f"{file_label}_tod_filt.png"))
    plt.close()


def plot_focal_plane(focal_plane: AxisManager, fit_plot_dir: str, ufm: str):
    """
    Plot the results of a the focal plane fit.
    We assume here that all angular values are in radians
    and the amplitude is in pW.

    The following plots will be made:

    * Xi vs Eta scatter, file = "{ufm}_fp.png"
    * Az vs El scatter, file = "{ufm}_enc.png"
    * amplitude histogram, "{ufm}_fp_amp.png"
    * FWHM histogram, "{ufm}_fp_fwhm.png"
    * Hits histogram, "{ufm}_fp_hits.png"
    * Reduced Chi Squared histogram, "{ufm}_fp_red_chisq.png"
    * R^2 histogram, "{ufm}_fp_r2.png"

    Parameters
    ----------
    focal_plane : AxisManager
        The fit focal plane.
        Should contain the following fit parameters (all with the same number of elements):
        `xi`, `eta`, `az`, `el`, `amp`, `fwhm`, `hits`, `reduced_chisq`, `R2`.
    fit_plot_dir : str
        The directory to save plots to.
    ufm : str
        The UFM that was fit.
        Used to determine filenames (see above).
    """
    plt.close()

    plt.scatter(np.array(focal_plane.xi), np.array(focal_plane.eta), alpha=0.25)
    plt.xlabel("Xi (rad)")
    plt.ylabel("Eta (rad)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_fp.png"))
    plt.close()

    plt.scatter(np.array(focal_plane.az), np.array(focal_plane.el), alpha=0.25)
    plt.xlabel("Az (rad)")
    plt.ylabel("El (rad)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_enc.png"))
    plt.close()

    plt.hist(np.array(focal_plane.amp), bins=30, alpha=0.25)
    plt.xlabel("Amp (pW)")
    plt.ylabel("Dets (#)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_fp_amp.png"))
    plt.close()

    plt.hist(np.array(focal_plane.fwhm), bins=30, alpha=0.25)
    plt.xlabel("FWHM (rad)")
    plt.ylabel("Dets (#)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_fp_fwhm.png"))
    plt.close()

    plt.hist(np.array(focal_plane.hits), bins=30, alpha=0.25)
    plt.xlabel("Hits (#)")
    plt.ylabel("Dets (#)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_fp_hits.png"))
    plt.close()

    plt.hist(np.array(focal_plane.reduced_chisq), bins=30, alpha=0.25)
    plt.xlabel("Reduced Chi Squared")
    plt.ylabel("Dets (#)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_fp_red_chisq.png"))
    plt.close()

    plt.hist(np.array(focal_plane.R2), bins=30, alpha=0.25)
    plt.xlabel("R2")
    plt.ylabel("Dets (#)")
    plt.savefig(os.path.join(fit_plot_dir, f"{ufm}_fp_r2.png"))
    plt.close()
