source: "mars"
min_samps: 20000
min_dets: 50
context: '/global/cfs/cdirs/sobs/users/skh/data/first_light_unfocused/source_fits/pointing_nersc.yaml'
start_time: 1739923200 
stop_time: 1845020800 # To be changed...
n_med: 3
mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - .1 
