map_source_list:
  - "mars"
  - "saturn"
  - "neptune"
  - "uranus"
  - "taua"
  - "3c279"
fit_source_list:
  - "mars"
  - "neptune"
  - "uranus"
  - "saturn"
  - "3c279"
pointing_type: "pointing_model" 
preprocess_cfg: "preproc/preproc_atm.yaml"
min_det_secs: 300
min_dets: 50
min_hits: 1
min_snr: 1
ctx_path: 'contexts/nersc_pointing_model_atm.yaml'
start_time: 1749600000 
stop_time: 1767243600 
n_med: 3
map_mask_size: 1.
apply_fscale: False
search_mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - .5
epochs:
    - [1749600000, 1756699200]
    - [1756699200, 1767243600]
append: "atm_relcal_wide"
cgiters_single: 0
cgiters_full: 200
mlpass: 3
sym_gauss: False
n_bessel: 25
n_multipoles: 8
bessel_wing_n_sigma: 3
extent: 300
det_split_dir: "det_lists"
gauss_multipole: False
metasplits:
  nosaturn:
    - "source"
    - ["mars", "uranus", "neptune"]
split_by:
  - "band"
  - "tube_slot+band"
  - "source+band"
  - "nosaturn+band"
  - "source+tube_slot+band"
  - "nosaturn+tube_slot+band"
det_splits:
  - inout0
  - inout1
  - left
  - right
