source: "mars"
min_samps: 100 #225000
context: '/so/metadata/lat/contexts/smurf_detcal.yaml'
start_time: 1741816800 
stop_time: 1741863600
xi_off: 0.0
eta_off: .007
try_all: True
n_med: 3
mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - .6
