source: "mars"
min_samps: 20000
context: '/so/metadata/lat/contexts/smurf_detcal.yaml'
# start_time: 1739923200 # First light 
# start_time: 1744848000 # Everything aligned
start_time: 1746187200 # Corotator moved
# start_time: 1748476800 # Autoschedular
stop_time: 2748476800
try_all: True
n_med: 5
mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - 1.5 
project_dir: 'pointing/lat'
nominal: '/so/home/saianeesh/data/pointing/lat/nominal/focal_plane.h5'
