source: "mars"
min_samps: 225000
context: '/so/metadata/lat/contexts/smurf_detcal.yaml'
start_time: 1739923200 
stop_time: 1745020800 # To be changed...
xi_off: 0.
eta_off: .013
try_all: True
n_med: 3
