fit_source_list:
  - "mars"
  - "saturn"
  - "uranus"
  - "neptune"
  - "jupiter"
  - "3c279"
min_samps: 5000
ctx_path: '/global/cfs/cdirs/sobs/metadata/lat/contexts/smurf_detcal_local.yaml'
preprocess_cfg: "preproc/preproc_fit_point.yaml"
nominal_path: '/global/cfs/cdirs/sobs/users/skh/data/pointing/lat/nominal/ID9/focal_plane.h5'

start_time: 1739923200 # First light 
# start_time: 1744848000 # Everything aligned
# start_time: 1745150000
# stop_time: 1746187200 # Corotator moved
# start_time: 1748476800 # Autoschedular
# start_time: 1756699200
# start_time: 1767243600 
stop_time: 1780340932 # 20000000000

ds: 1

nominal_fwhm: # arcmin LAT; change per platform
  f030: 7.4
  f040: 5.1
  f090: 2
  f150: 1.3
  f220: 0.95
  f280: 0.83
    
try_all: True 

hp_fc: 1
lp_fc: 30

min_hits: 1
svd_modes: 10
min_dets: 10

src_msk: True # False
blind_search: True # False
pointing_mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - 2.5 

fit_pars:
  bin_priors: True 
  min_snr: 3

fwhm_tol_pointing: .6
