source: "rcw38"
min_samps: 20000
context: '/so/metadata/lat/contexts/smurf_detcal.yaml'
# context: '/global/cfs/cdirs/sobs/metadata/lat/contexts/smurf_detcal_local.yaml'
start_time: 1743983519 
stop_time: 1845020800 # To be changed...
xi_off: 0.
eta_off: 0 #.01
try_all: True
n_med: 5
mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - 3 
