source: "saturn"
min_samps: 20000
context: '/global/cfs/cdirs/sobs/metadata/lat/contexts/smurf_detcal_local.yaml'
start_time: 1739923200 # First light 
# start_time: 1744848000 # Everything aligned
# start_time: 1746187200 # Corotator moved
# start_time: 1748476800 # Autoschedular
stop_time: 2748476800
try_all: True
n_med: 5
mask:
  shape: "circle"
  xyr:
    - 0.
    - 0.
    - 1.5 
project_dir: 'pointing/lat'
nominal: '/global/cfs/cdirs/sobs/users/skh/data/pointing/lat/nominal/focal_plane.h5'
src_msk: False
fwhm: # arcmin LAT; change per platform
  f090: 2
  f150: 1.3
  f220: 0.95
  f280: 0.83
    
