fit_source_list:
  #- "saturn"
  - "jupiter"
  #- "moon"
min_samps: 5000

#ctx_path: '/scratch/gpfs/SIMONSOBS/so/tracked/metadata/satp3/contexts/use_this_local.yaml'
ctx_path: '/scratch/gpfs/SIMONSOBS/users/eshaw/mymetadata/satp3/context_for_fitpointing.yaml'
preprocess_cfg: "/scratch/gpfs/SIMONSOBS/users/eshaw/repos/LAT_beams/preproc/preproc_fit_point_jupiter_sat3_tiger.yaml"
nominal_path: '/scratch/gpfs/SIMONSOBS/users/eshaw/ffp_per_obs/satp3/nominal/nominal.h5'
root_dir: '/scratch/gpfs/SIMONSOBS/users/eshaw/lattype_process_brightsrc/'

tel: "satp3"


start_time: 1723197800
stop_time: 1723292800

#Test Jupiter: 

#obs_1727850236_satp3_1111111, #ws1
#obs_1727936444_satp3_1111111, #ws1
#obs_1761117697_satp3_1111111, #ws1  start_time: 1761117500 stop_time: 1761118000
#obs_1728714036_satp3_1011111, #ws2
#obs_1729144572_satp3_1011111, #ws6
#obs_1759570664_satp3_1111111, #ws4


#obs_1723465113_satp3_1111111 #jupiter and mars? #ws6
#'obs_1723124459_satp3_1011111' #ws6 Jupiter and mars overlap
#ws2




#plot_only: True
forced_ws: 'ws6'

ds: 1

nominal_fwhm: # arcmin LAT; change per platform
  f090: 28.6
  f150: 19.6
    
try_all: False


#maybe remove the high pass? 
hp_fc: 0.0005
lp_fc: 1.1

min_hits: 5
svd_modes: 0 #10
min_dets: 10

src_msk: False
blind_search: True
pointing_mask:
  shape: "circle"
  xyr:
    - 0 #-0.013 #satp3 az offset
    - 0.
    - 8 #or 2.5 (LAT)

fit_pars:
  bin_priors: True 
  min_snr: 3

fwhm_tol_pointing: 100 #.6
n_std: 5 #10
n_med: 5 #10

trim_samps: 4000
